server:
  port: 8084

spring:
  application:
    name: APIGATEWAY


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
           - Path=/users/**
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
           - Path=/hotels/**
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
           - Path=/ratings/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#okta configuration for api gateway
okta:
  oauth2:
    issuer: https://dev-26778634.okta.com/oauth2/default
    audience: api://default
    client-id: 0oahdkhbsm1TuYEKl5d7
    client-secret: IR6SzUmvhKZRsjaqXuIB6nVgdiHEWTJd0YyAj_vfrrMhsFQq4JUR2eXMbIbEe8s4
    scopes: openid, profile, email, offline_access